### ISSUE TITLE
Longer show names get wrapped in the top bar

### ISSUE THREAD

**Issue by thelovebug** [othersidenetwork/otherside.network#2]
Longer show names are currently being wrapped in the drop-down menu on the top bar.  This is probably because we've never had a show name that long before.  

![Wrapped Show Name](https://user-images.githubusercontent.com/2915687/64061593-068eb880-cbd5-11e9-8479-76fb104d7c78.png)

Is it possible to auto-size based on the content length?  What would happen if we replaced spaces with `&nbsp;`?  Would it truncate or bleed?

Also, there's a line in `normalize.less` which uses an apparently invalid CSS property: `-webkit-text-size-adjust` - this might be relevant?

**Comment by ymauray** [comment]
Did you change something ? I see this :

![image](https://user-images.githubusercontent.com/2527227/65422148-f2ba2900-de05-11e9-9608-adc5c25be518.png)

**Comment by ymauray** [comment]
Ha ! the font is different. Got it now.

**Comment by thelovebug** [comment]
Confirmed that this is now fixed on my side (now that the Github Updater is fixed also!)
